/datum/unit_test/liquid_lava_viscosity/Run()
	var/turf/water_source = locate(20, 20, 1).ChangeTurf(/turf/open/floor/rogue/cobble, null, CHANGETURF_IGNORE_AIR)
	if(!water_source.cell)
		water_source.cell = new /cell(water_source)
		water_source.cell.InitLiquids()
	var/turf/water_neighbor = get_step(water_source, EAST)
	TEST_ASSERT_NOTNULL(water_neighbor, "viscosity test needs an adjacent turf for the water pair")
	water_neighbor = water_neighbor.ChangeTurf(/turf/open/floor/rogue/cobble, null, CHANGETURF_IGNORE_AIR)
	if(!water_neighbor.cell)
		water_neighbor.cell = new /cell(water_neighbor)
		water_neighbor.cell.InitLiquids()
	SSliquid.clear_cell_fluid(water_source)
	SSliquid.clear_cell_fluid(water_neighbor)
	SSliquid.NativeFire()
	var/water_src_native = vn_fluid_total(water_source.x, water_source.y, water_source.z)
	var/water_neighbor_native = vn_fluid_total(water_neighbor.x, water_neighbor.y, water_neighbor.z)
	TEST_ASSERT_EQUAL(water_src_native, 0, "water viscosity pair source must start dry")
	TEST_ASSERT_EQUAL(water_neighbor_native, 0, "water viscosity pair neighbor must start dry")

	var/datum/liquid/water_fluid = water_source.cell.get_fluid_datum(WATER)
	TEST_ASSERT_NOTNULL(water_fluid, "viscosity test source turf must have a water fluid datum")
	SSliquid.manager.add_fluid(water_source, water_fluid, 100)

	var/const_pumps = 8
	for(var/i in 1 to const_pumps)
		SSliquid.NativeFire()
		sleep(1)
	var/water_neighbor_sum = water_neighbor.cell.fluidsum

	SSliquid.clear_cell_fluid(water_source)
	SSliquid.clear_cell_fluid(water_neighbor)
	SSliquid.NativeFire()

	var/turf/lava_source = locate(20, 30, 1).ChangeTurf(/turf/open/floor/rogue/cobble, null, CHANGETURF_IGNORE_AIR)
	if(!lava_source.cell)
		lava_source.cell = new /cell(lava_source)
		lava_source.cell.InitLiquids()
	var/turf/lava_neighbor = get_step(lava_source, EAST)
	TEST_ASSERT_NOTNULL(lava_neighbor, "viscosity test needs an adjacent turf for the lava pair")
	lava_neighbor = lava_neighbor.ChangeTurf(/turf/open/floor/rogue/cobble, null, CHANGETURF_IGNORE_AIR)
	if(!lava_neighbor.cell)
		lava_neighbor.cell = new /cell(lava_neighbor)
		lava_neighbor.cell.InitLiquids()
	SSliquid.clear_cell_fluid(lava_source)
	SSliquid.clear_cell_fluid(lava_neighbor)
	SSliquid.NativeFire()
	var/lava_src_native = vn_fluid_total(lava_source.x, lava_source.y, lava_source.z)
	var/lava_neighbor_native = vn_fluid_total(lava_neighbor.x, lava_neighbor.y, lava_neighbor.z)
	TEST_ASSERT_EQUAL(lava_src_native, 0, "lava viscosity pair source must start dry")
	TEST_ASSERT_EQUAL(lava_neighbor_native, 0, "lava viscosity pair neighbor must start dry")

	var/datum/liquid/lava_fluid = lava_source.cell.get_fluid_datum(/datum/liquid/lava)
	TEST_ASSERT_NOTNULL(lava_fluid, "viscosity test source turf must have a lava fluid datum")
	SSliquid.manager.add_fluid(lava_source, lava_fluid, 100)

	for(var/i in 1 to const_pumps)
		SSliquid.NativeFire()
		sleep(1)
	var/lava_neighbor_sum = lava_neighbor.cell.fluidsum

	TEST_ASSERT(water_neighbor_sum > 0, "water source must spread some fluid onto its neighbor within [const_pumps] pumps")
	TEST_ASSERT(water_neighbor_sum > lava_neighbor_sum, "lava's lower flow_permille must transfer strictly less volume than water in the same [const_pumps] pumps (water=[water_neighbor_sum] lava=[lava_neighbor_sum])")

	SSliquid.clear_cell_fluid(lava_source)
	SSliquid.clear_cell_fluid(lava_neighbor)
	SSliquid.NativeFire()
